<?php
/**
 * Created by PhpStorm.
 * User: zima
 * Date: 11.01.2020
 * Time: 1:13
 */

namespace backend\widgets;


use yii\base\Widget;

class AppleGenerateWidget extends Widget
{

    /**
     * @var int
     */
    public $defaultCount = 5;

    /**
     *
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('apple-generate/index', [
            'defaultCount' => $this->defaultCount,
        ]);
    }
}