<?php
/**
 * Created by PhpStorm.
 * User: zima
 * Date: 11.01.2020
 * Time: 1:13
 */

namespace backend\widgets;

use common\models\Apple;
use yii\base\Widget;

/**
 * Class AppleStatWidget
 * @package backend\widgets
 */
class AppleStatWidget extends Widget
{
    /**
     *
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $stat = [
            'total' => Apple::find()->count(),
            'active' => Apple::find()->active()->count(),
            'new' => Apple::find()->status(Apple::STATUS_NEW)->count(),
            'down' => Apple::find()->status(Apple::STATUS_DOWN)->count(),
            'rotten' => Apple::find()->status(Apple::STATUS_ROTTEN)->count(),
            'eaten' => Apple::find()->status(Apple::STATUS_EATEN)->count(),

        ];

        return $this->render('apple-stat/index', [
            'stat' => $stat,
        ]);
    }
}