<?php
/**
 * Created by PhpStorm.
 * User: zima
 * Date: 11.01.2020
 * Time: 1:13
 */

namespace backend\widgets;

use yii\base\Widget;

/**
 * Class AppleGenerateWidget
 * @package backend\widgets
 */
class AppleGenerateWidget extends Widget
{
    /**
     * @var bool
     */
    public $enableManual = true;

    /**
     * @var int
     */
    public $maxCount = 10;

    /**
     *
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        return $this->render('apple-generate/index', [
            'enableManual' => (int)$this->enableManual,
            'maxCount' => $this->maxCount,
        ]);
    }
}